# Generated by Django 4.2 on 2023-04-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_feeding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeding",
            name="meal",
            field=models.CharField(
                choices=[("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner")],
                default="B",
            ),
        ),
    ]
