# Generated by Django 4.2 on 2023-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_feeding_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeding",
            name="meal",
            field=models.CharField(
                choices=[("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner")],
                default="B",
                max_length=1,
            ),
        ),
    ]
